export const members = [
  { id: 1, name: 'Ahmad Raihan Maulana Setiawan', subdomain: 'aren' },
  { id: 2, name: 'Andini Azaria Zahra', subdomain: 'andini' },
  { id: 3, name: 'Arrosyid Al Ayubi', subdomain: 'arrosyid' },
  { id: 4, name: 'Arum Kusuma Dewi', subdomain: 'arum' },
  { id: 5, name: 'Azzura Agustina', subdomain: 'azzura' },
  { id: 6, name: 'Diaz Prasojo', subdomain: 'diaz' },
  { id: 7, name: 'Diaz Shandika Firdaus', subdomain: 'dika' },
  { id: 8, name: 'Gladys Aditya Ramadhan', subdomain: 'gladys' },
  { id: 9, name: 'Farah Hilallia Alvina', subdomain: 'farah' },
  { id: 10, name: 'Haikal Azhar', subdomain: 'haikal' },
  { id: 11, name: 'Harsya Pandawa', subdomain: 'harsya' },
  { id: 12, name: 'Hisyam Arief Firmansyah', subdomain: 'hisyam' },
  { id: 13, name: 'Ihwan Ramadani', subdomain: 'ihwan' },
  { id: 14, name: 'Isma Khoyriyah', subdomain: 'isma' },
  { id: 15, name: 'Liza Zulaikha', subdomain: 'liza' },
  { id: 16, name: 'Maylova Chayananda', subdomain: 'maylova' },
  { id: 17, name: 'Muhamad Gilang Ramadan', subdomain: 'gilang' },
  { id: 18, name: 'Muhammad Rizqi Rahman', subdomain: 'rizqi' },
  { id: 19, name: 'Muhammad Shandi Yudha', subdomain: 'shandi' },
  { id: 20, name: 'Muhammad Zaky Permana', subdomain: 'zaky' },
  { id: 21, name: 'Rayhan Priyonggo', subdomain: 'rayhan' },
  { id: 22, name: 'Refael Gomgom Sibarani', subdomain: 'refael' },
  { id: 23, name: 'Rifky Chaezario Hidayat', subdomain: 'rifky' },
  { id: 24, name: 'Rizka Nur Juniarti', subdomain: 'rizka' },
  { id: 25, name: 'Rizky Nur Rahman', subdomain: 'rizky' },
  { id: 26, name: 'Sultan Muhammad Syafiq', subdomain: 'sultan' },
  { id: 27, name: 'Surya Aji Prasetya', subdomain: 'surya' },
  { id: 28, name: 'Zaqi Alfataillah', subdomain: 'zaqi' },
];